/* Generated By: Maker.jj,v 1.3 1997/11/22 07&JavaCC: Do not edit this line. MakerConstants.java */
package cryptix.util.test;

public interface MakerConstants {

  int EOF = 0;
  int COMMENT = 6;
  int MESSAGE_DIGEST = 7;
  int CIPHER = 8;
  int PROPERTIES = 9;
  int DATA = 10;
  int MODE = 11;
  int PADDING = 12;
  int IV = 13;
  int AUTO = 14;
  int SPEED = 15;
  int INCLUDE = 16;
  int HEX_LITERAL = 18;
  int ID = 20;
  int PROPERTY = 21;
  int LETTER = 22;
  int DIGIT = 23;
  int NUMBER = 24;
  int STRING_LITERAL = 25;

  int DEFAULT = 0;
  int IN_HEX_LITERAL = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "\"md\"",
    "\"cipher\"",
    "<PROPERTIES>",
    "\"data\"",
    "\"mode\"",
    "\"padding\"",
    "\"iv\"",
    "\"auto\"",
    "\"speed\"",
    "\"include\"",
    "\"<\"",
    "\">\"",
    "<token of kind 19>",
    "<ID>",
    "<PROPERTY>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<STRING_LITERAL>",
    "\"*\"",
    "\"=\"",
  };

}
