// Copy any of these definitions to modules that need to call KEY.CPP
// routines for function and special keys. These definitions could be
// included in key.h, but I removed them to conserve memory for the
// compiler.

#define KEY_F1    -197     // Function keys
#define KEY_F2    -196
#define KEY_F3    -195
#define KEY_F4    -194
#define KEY_F5    -193
#define KEY_F6    -192
#define KEY_F7    -191
#define KEY_F8    -190
#define KEY_F9    -189
#define KEY_F10   -188
#define KEY_F11   -123     // Not recognized on all systems
#define KEY_F12   -122     // "     "     "     "     "

#define KEY_HOME  -185     // Special-purpose keys
#define KEY_UP    -184
#define KEY_PGUP  -183
#define KEY_PAGE_UP  -183
#define KEY_LEFT  -181
#define KEY_RIGHT -179
#define KEY_END   -177
#define KEY_DOWN  -176
#define KEY_PGDN  -175
#define KEY_PAGE_DOWN  -175
#define KEY_INS   -174
#define KEY_DEL   -173

#define KEY_ESC   0x1b	//27	//escape key
#define KEY_TAB   0x09	//tab key
#define KEY_D     0x44	//tab key
#define KEY_d     0x64  //tab key
// Copyright (c) 1990,1992 by Tom Swan. All rights reserved
// Revision 1.00    Date: 10/26/1990   Time: 10:05 am
// Revision 2.00    Date: 05/28/1992   Time: 04:35 pm
