/*
 * Copyright (C) 1997 Pretty Good Privacy, Inc.  All rights reserved.
 *
 * $Id$
 */

// STDINC.H - project invariants

#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <richedit.h>
#include <tchar.h>

#if 0

// Support dimensionless arrays for convenience.

#define MAPI_DIM 0
#pragma warning (disable:4200)
#endif

#include <mapix.h>
#include <mapiutil.h>
#include <mapiform.h>
#include <exchext.h>
#include <exchext.h>
#include <exchext.h>
