.\"                                                                   
.\" Filename:      add_sig.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:45:53 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   


.Dd May 17, 1997
.Dt ADD_SIG 3
.Os PGPlib
.Sh NAME
.Nm add_sig
.Nd add a UID to a public key
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn add_sig "PGPKEYID key" "PGPuserid_t *uid" "PGPsig_t *sig"
.Sh DESCRIPTION
Retrieves the public key
.Fa key .
If the key is found the 
.Fa sig
is added (at the end, if not present) and the key again stored in the
database.  The signature is not validated against the available
UID's. 
\.
.Sh RETURN VALUES
If the update was successful, 0 is returned.
If
.Fa key
could not be found  1 is returned.
If the signature was already present, 2 is returned.
If an error occured, -1 is returned.
\.
.Sh SEE ALSO
.Xr get_keyentry_from_buf PGPlib
.Xr get_pubkey_rec PGPlib
.Xr signature2buf PGPlib
.Xf store_pub_key_rec PGPlib
.Xr PGPlib 3
\.
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
