.\"                                                                   
.\" Filename:      bufgets.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Nov  8 17:43:38 1997
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   

.Dd May 17, 1997
.Dt BUFGETS 3
.Os PGPlib
.Sh NAME
.Nm bufgets
.Nd get a line from a buffer
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn bufgets "u_char *line" "int linelen" "u_char *buf" "int buflen"
.Sh DESCRIPTION
Copy at most
.Fa linelen 
- 1 bytes from buffer into 
.Fa line , 
stopping after the first newline has been found or 
.Fa buflen 
bytes have been copied.  In any case, a NULL is appended to the string.
.Pp
.Sh RETURN VALUES
If some parameter is unreasonable, 0 is returned, if not, the 
number of bytes consumed from buf is returned.
If a one-byte line is passed in, 0 will obviously be returned.
.Pp
.Sh SEE ALSO
.Xr fgets 3
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1.
