.\"                                                                   
.\" Filename:      key_exists.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:45:04 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" (C) 1997 Tage Stabell-Kulø, all rights reserved.
.\"                                                                   


.Dd May 17, 1997
.Dt KEY_EXISTS 3
.Os PGPlib
.Sh NAME
.Nm key_exists
.Nd check whether a public key is known
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn key_exists "PGPKEYID key"
.Sh DESCRIPTION
Probes the database for the values of
.Fa key .
.Pp
.Sh RETURN VALUES
If
.Fa key
is in the database 1 is returned, if not, 0 is returned.
Upon error, -1 is returned.
.Pp
.Sh SEE ALSO
.Xr keydb_init PGPlib
.Xr PGPlib
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
