.\"                                                                   
.\" Filename:      pke.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Fri Jul 25 09:22:06 1997
.\" Modified by:   Tage Stabell-Kulo <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   

.Dd May 17, 1997
.Dt PKE 3
.Os PGPlib
.Sh NAME
.Nm pke
.Nd routines to manipulate packets encrypted with a public key
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn buf2pke "u_char *buf" "int len" "PGPpke_t *pke"
.Ft void
.Fn free_pke "PGPpke_t *pke"
.Sh DESCRIPTION
The routine
.Fn buf2pke
parses the buffer
.Fa buf ,
which must contain a PGP PKE packet, and fills in the relevant parts
in the structure pointed to by
.Fa pke .
In the same manner as 
.Fn buf2pke
does not allocate space for the structure,
.Fn free_pke
only frees the internal state (not the space occupied by the structure
itself).
.Pp
.Sh RETURN VALUES
Upon success 0 is returned.  If an error occurs, -1 is returned.
.Fn buf2pke
will return 1 if there was a syntax error in the input.
.Pp
.Sh SEE ALSO
.Xr malloc 3
.Xr free 3
.Xr PGPlib 3
.Pp
.Sh HISTORY
Written by Thomas Roessler <roessler@guug.de>.  First appeared in
PGPlib 0.3.
