.\"                                                                   
.\" Filename:      pub_fingerprint.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat May 24 16:25:37 1997
.\" Modified by:   Tage Stabell-Kulo <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   


.Dd May 17, 1997
.Dt PUB_FINGERPRINT 3
.Os PGPlib
.Sh NAME
.Nm pub_fingerprint
.Nd print the "fingerprint" of
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn pub_fingerprint "PGPpubkey_t *key" "char str[50]"
.Sh DESCRIPTION
The "fingerprint" of
.Fa key
is calculated and stored in
.Fa str .
The "fingerprint" is calculated over the binary
representation of the values
.Fa N
and
.Fa E
by means of MD5.  The resulting string has fixed length (50) and is
not null-terminated.
.Pp
.Sh RETURN VALUES
If an error occured, -1 is returned, if not, 0 is returned.
.Pp
.Sh SEE ALSO
.Xr PGPlib 3
.Pp
.Sh BUGS
The size of the key should have been included in the fingerprint.
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.2.
