.\"                                                                   
.\" Filename:      seckey.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Nov  8 18:53:22 1997
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   

.Dd May 17, 1997
.Dt SECKEY 3
.Os PGPlib
.Sh NAME
.Nm seckey
.Nd routines to manipulate secret keys
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn buf2seckey "u_char *buf" "int len" "PGPseckey_t *key"
.Ft void
.Fn free_seckey "PGPseckey_t *key"
.Ft void
.Fn print_seckey "int verbose" "FILE *fd" "PGPseckey_t *key"
.Sh DESCRIPTION
The routine
.Fn buf2seckey
parses the buffer
.Fa buf ,
which must contain a PGP secret key, and fills in the relevant parts
of the structure pointed to by
.Fa key .
The secret fields in the key are not decrypted.
In the same manner as 
.Fn buf2_seckey
does not allocate space for the structure,
.Fn free_seckey
only frees the internal state (not the space occupied by the structure
itself).
.Fn print_seckey
is for debugging purposes only; use it with the outmost care !
.\
.Sh RETURN VALUES
Upon success 0 is returned.  If an error occurs, -1 is returned.
.Fn buf2seckey 
will return 1 if there was a syntax error in the input.
.Pp
.Sh SEE ALSO
.Xr free 3
.Xr malloc 3
.Xr decrypt_seckey PGPlib
.Xr PGPlib 3
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
