.\"                                                                   
.\" Filename:      store_pubkey.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Nov  8 19:03:46 1997
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" (C) 1997 Tage Stabell-Kulø, all rights reserved.
.\"                                                                   

.Dd May 17, 1997
.Dt STORE_PUBKEY 3
.Os PGPlib
.Sh NAME
.Nm store_pubkey
.Nd store a public key
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn store_pubkey "PGPpubkey_t key" "repl_t replace"
.Sh DESCRIPTION
The public key
.Fa key
is stored in the database.
If the key, identified by the key identifier (64 bits) is already
present in the database, the action depends on the value of 
.Fa replace .
This value can be either 
.Fa INSERT
or
.Fa REPLACE 
with the obvious meanings.
In addition to storage of the actual key, the "short" identifier is
also extracted and added to the database for later retrieval.
.Pp
.Sh RETURN VALUES
If no error occured, 0 is returned.  If the key itself was added but
there was a problem adding the "short" key identifier, 1 is returned.
On error, -1 is returned.
.Pp
.Sh SEE ALSO
.Xr dbopen 3
.Xr find_shortid PGPlib
.Xr keydb_init PGPlib
.Xr store_pubkey_record PGPlib
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
                                                                    
