.\"                                                                   
.\" Filename:      store_uid.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:45:36 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   


.Dd May 17, 1997
.Dt STORE_UID 3
.Os PGPlib
.Sh NAME
.Nm store_uid
.Nd add a UID to a public key
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn store_uid "PGPuserid_t uid" "PGPKEYID id"
.Sh DESCRIPTION
First, the
.Fa uid
is added the database of UID's under the index
.Fa id .
Then, the 
.Fa id
is added to the reverse-string database with the 
.Fa uid
as index.
Last, the public key
.Fa id
is retrieved and
.Fa uid
added to it (if not already there).
.Pp
.Sh RETURN VALUES
If the uid was sucessfully added to the key, 0 is returned.  If the
key
.Fa id
could not be found, 1 is returned.
Upon error, -1 is returned.
.Pp
.Sh SEE ALSO
.Xr PGPlib
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
