From jefft@netcom.com Wed Sep 14 00:18:25 1994
Received: from netcom7.netcom.com by scss3.cl.msu.edu (4.1/4.7)  id AA27433; Wed, 14 Sep 94 00:18:21 EDT
Received: by netcom7.netcom.com (8.6.8.1/Netcom)
	id VAA17329; Tue, 13 Sep 1994 21:11:08 -0700
Date: Tue, 13 Sep 1994 21:11:08 -0700
From: jefft@netcom.com (Jeff Thompson)
Message-Id: <199409140411.VAA17329@netcom7.netcom.com>
To: mrr@scss3.cl.msu.edu
In-Reply-To: <9409120405.AA23274@scss3.cl.msu.edu> (message from Mark Riordan on Mon, 12 Sep 94 00:05:39 EDT)
Subject: Re: RIPEM 2.0b2
Status: OR


> Thanks for the files.  I have cleaned up some of the
> old doc files & made Microsoft C .mak files.
> When I compile under DOS, though, I get a RIPEM.EXE
> that, when run from testd.bat, complains:
> 
> Could not find CertificateInfo keyValue test in file
> 
> and then locks up the system, requiring a reboot.
> 
> Any ideas?

I tried it out on a friend's installation of Visual C++ 1.0 and it
seems to work fine, even with testd.bat.  I have included a zip file
with the makefile I used.  It is just like the Borland makefile but
modified for Microsoft C.  Note that it uses -D__STDC__ on the command
line.  This was necessary to get headers.h to use the right string
concatenating macros.  If there is some better way to get it to use
the right ones, then -D__STDC__ can be removed.

Also included is getsys.c as I had to modify it to compile.  The only
difference is it doesn't try to define MSDOS again if ripem.h already
defined it, and it #includes direct.h, not dir.h (which Borland uses).

- Jeff

