/*
 *
 * $Id: wvdlg.h 1.7 1993/06/22 19:09:14 rushing Exp $
 * $Log: wvdlg.h $
 * Revision 1.7  1993/06/22  19:09:14  rushing
 * mail force type selection via dialog
 *
 * Revision 1.6  1993/06/22  18:14:53  rushing
 * added ID's for MailForceType
 *
 * Revision 1.5  1993/05/28  17:18:00  rushing
 * Added Misc... option to enable threading
 *
 * Revision 1.4  1993/05/18  22:10:45  rushing
 * smtp support
 *
 * Revision 1.3  1993/05/13  19:58:51  SOMEONE
 * fancy 'from' in group window
 *
 * Revision 1.2  1993/05/13  16:17:30  rushing
 * article fetch limit dialog box support
 *
 * Revision 1.1  1993/02/16  20:54:42  rushing
 * Initial revision
 *
 *
 */

#define ID_CANCEL                      2
#define ID_COMMSERIAL                  306
#define ID_COMMTCP                     305
#define ID_CONFIG_APPEND               342
#define ID_CONFIG_ARTICLE_FIXED_FONT   352
#define ID_CONFIG_ASK_COMM             350
#define ID_CONFIG_DO_LIST              344
#define ID_CONFIG_EMAIL                321
#define ID_CONFIG_NAME                 320
#define ID_CONFIG_NEW_WND_ARTICLE      341
#define ID_CONFIG_NEW_WND_GROUP        340
#define ID_CONFIG_NNTP_PORT            311
#define ID_CONFIG_NNTP_SERVER          310
#define ID_CONFIG_ORG                  322
#define ID_DOLIST_ASK                  332
#define ID_DOLIST_BASE                 330
#define ID_DOLIST_NO                   333
#define ID_DOLIST_YES                  331
#define ID_OK                          1
#define ID_OK_SAVE                     11
#define IDD_7EVEN                      302
#define IDD_8NONE                      303
#define IDD_APPEND                     502
#define IDD_COM1                       300
#define IDD_COM2                       301
#define IDD_FILENAME                   501
#define IDD_GROUP_LISTBOX              507
#define IDD_OK_SAVE                    109
#define IDD_SEARCH_STRING              510
#define IDD_SPEED                      304

#define IDD_PRINT                      600
#define IDD_PRINTDEVICE                601     /* JD 930205 */
#define IDD_PRINTPORT                  602     /* JD 930205 */
#define IDD_PRINTTITLE                 603     /* JD 930205 */

#define IDD_SUBJECT_STRING          511
#define IDD_ART_THRESHOLD           655
#define IDD_ARTS_TO_GRAB            656
#define ID_THRESHOLD_ALL            654
#define ID_100_ARTS                 650
#define ID_250_ARTS                 651
#define ID_500_ARTS                 652
#define OK                          108
#define ID_CONFIG_FULLNAMEFROM      512
#define IDD_SUBJECT_PROMPT          513
#define ID_CONFIG_SMTP_SERVER       514
#define ID_CONFIG_THREADS           334
#define IDD_MAIL_SELECT_NONE        515
#define IDD_MAIL_SELECT_MAPI        516
#define IDD_MAIL_SELECT_SMTP        517
#define IDD_MAIL_SELECT_AUTO        518

#define ID_CONFIG_AUTH_USERNAME     521
#define ID_CONFIG_AUTH_PASSWORD     522
