.\"
.\" pgpk.1
.\"
.\" Copyright (C) 1997 Pretty Good Privacy, Inc.  All rights reserved.
.\"
.\" $Id: pgpk.1,v 1.1.2.3.2.3 1997/07/14 14:16:07 quark Exp $
.\"
.\" Process this file with
.\" groff -man -Tascii pgpe.1
.\"
.TH PGP 5.0 "JULY 1997 (v5.0)" PGP "User Manual"
.SH NAME
pgpk \- Public and Private key management for PGP.
.SH SYNOPSIS
.B pgpk
.BI [-a " keyfile ..." " |
.B -c [userid]] |
.B -d <userid> | \p
.B -e <userid> |
.B -g |
.B -l[l] [userid] |
.B --revoke[s]  <userid> |
.B -r[u|s] <userid> |
.B -s <userid> [-u <yourid>] | \p
.B -x <userid>]
.BI [-o " <outfile>" ]
.B [-z]
.br

.SH DESCRIPTION
.B pgpk
Manages public and private keys for PGP.  Unlike other PGP
applications, pgpk is stream based and not file based; if no files are
specified,
.I stdin
and
.I stdout
are used.
.SH OPTIONS
All configuration options can be controlled from the command line.
See
.BR pgp.cfg (5)
for a complete list and how to specify them.

.IP "-a [keyfile]"
Adds the contents of
.I keyfile
to your keyring.  If
.I keyfile
is not specified, input is taken from
.IR stdin.
.I Keyfile
may also be an URL; the supported protocols are
.B hkp
(Horowitz Key Protocol),
.B http
and
.BR finger .
To add
.BR foo@bar.baz.com 's
key to your keyring from PGP, Inc's server, for example, enter:

.I pgpk -a hkp://keys.pgp.com/foo@bar.baz.com

If
.B foo@bar.baz.com
has his key in his finger information, you could add that with:

.I pgpk -a finger://bar.baz.com/foo

If
.B foo@bar.baz.com
has his key on his web page, you could add that with:

.I pgpk -a http://www.baz.com/foo/DSSkey.html

.IP "-c [userid]"
Checks the signatures of all keys on your public keyring.  If
.B [userid]
is specified, only the signatures on that key are checked.
.IP "-d <userid>"
Toggles the disablement of
.BR <userid> 's
key on your public keyring.
.IP "-e <userid>"
Edits
.BR <userid> 's
key.  If this is your key, it allows you to edit your userid(s) and
passphrase.  If it is someone else's key, it allows you to edit the
trust you have in that person as an introducer.
.IP -g
Generate a public/private key pair.
.IP "-l[l] [userid]"
Lists information about a key.
.B -ll
lists more information about a key.  If
.B [userid]
is specified, that key is listed.  Otherwise, all keys are listed.
.IP "-o outfile"
Specifies that output should go to
.IR outfile .
If not specified, output goes to
.IR stdout .
If the output file is from a key extraction (see
.BR -x ,
below), you may specify an hkp (Horowitz Key Protocol) URL.  For
example:
.I pgpk -x foo@bar.baz.com -o hkp://keys.pgp.com
would send
.BR foo@bar.baz.com 's
key to the PGP, Inc. public key server.
.IP "--revoke <userid>"
.B Permanately
revokes the key specified.  There is no way to undo this, so don't
play with it if you don't mean it.
.IP "--revokes <userid>"
.B Permanently
revokes your signature (if any) on the key specified.
.IP "-r <userid>"
Removes
.BR <userid> 's
key from your public keyring, and your private as well, if it's there.
.IP "-ru <userid>"
Removes the given userid from your public and private keyrings.
.IP "-rs <userid>"
Removes the given signature from your public keyring.
.IP ".s <userid> [-u <yourid>]"
Signs
.BR <userid> 's
key with your default signing key.  If
.B -u
is specified, uses that key, instead.
.IP "-x <userid>"
Extracts the specified key in ASCII-armored form.
.B -x <userid>
.IP -z
Batch mode.  See
.BR pgp-integration (7)
for a discussion of integrating pgp support into your application.
.SH EXAMPLE
.I pgpk -g
Generates a key.
.RE
.SH FILES
.I ~/.pgp/pgp.cfg
.RS
User-specific configuration file.  In previous releases, this file was
called
.IR config.txt .
See
.BR pgp.cfg (5)
for further details.
.RE
.SH BUGS
.RS
See
.BR pgp (1).
.BE
.SH "SEE ALSO"
.BR pgp (1),
.BR pgpv (1),
.BR pgpe (1),
.BR pgps (1),
.BR pgp.cfg (5),\p
.BR pgp-integration (7),
http://www.pgp.com (US versions)
and
http://www.pgpi.com (International versions)
