.\"#	@(#)COPYRIGHT	1.1a (NRL) 17 August 1995
.\"
.\"COPYRIGHT NOTICE
.\"
.\"All of the documentation and software included in this software
.\"distribution from the US Naval Research Laboratory (NRL) are
.\"copyrighted by their respective developers.
.\"
.\"This software and documentation were developed at NRL by various
.\"people.  Those developers have each copyrighted the portions that they
.\"developed at NRL and have assigned All Rights for those portions to
.\"NRL.  Outside the USA, NRL also has copyright on the software
.\"developed at NRL. The affected files all contain specific copyright
.\"notices and those notices must be retained in any derived work.
.\"
.\"NRL LICENSE
.\"
.\"NRL grants permission for redistribution and use in source and binary
.\"forms, with or without modification, of the software and documentation
.\"created at NRL provided that the following conditions are met:
.\"
.\"1. Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\"2. Redistributions in binary form must reproduce the above copyright
.\"   notice, this list of conditions and the following disclaimer in the
.\"   documentation and/or other materials provided with the distribution.
.\"3. All advertising materials mentioning features or use of this software
.\"   must display the following acknowledgement:
.\"
.\"	This product includes software developed at the Information
.\"	Technology Division, US Naval Research Laboratory.
.\"
.\"4. Neither the name of the NRL nor the names of its contributors
.\"   may be used to endorse or promote products derived from this software
.\"   without specific prior written permission.
.\"
.\"THE SOFTWARE PROVIDED BY NRL IS PROVIDED BY NRL AND CONTRIBUTORS ``AS
.\"IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\"TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\"PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL NRL OR
.\"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"The views and conclusions contained in the software and documentation
.\"are those of the authors and should not be interpreted as representing
.\"official policies, either expressed or implied, of the US Naval
.\"Research Laboratory (NRL).
.\"
.\"----------------------------------------------------------------------*/
.\"
.\" @(#)addr2ascii 3	1.0 95/08/16
.TH ADDR2ASCII 3 "1 October 1995"
.SH NAME
addr2ascii,ascii2addr,hostname2addr,addr2hostname \- generic network name and address library functions
.SH SYNOPSIS
.ft B
.nf
int addr2ascii(int af, void *ap, int len, char *cp);
int ascii2addr(int af, char *cp, void *ap);
struct hostent *addr2hostname(void *addr, int len, int af);
struct hostent *hostname2addr(char *name, int af);
.fi
.SH DESCRIPTION
.B addr2ascii(\|)
converts an 
.IR AF_ISO , 
.IR AF_INET , or 
.IR AF_INET6 ,
address into printable form.
.br
.I af
specifies the address family of the address being converted.
.I ap
points to the address to convert.
.I len
is the length of the result.
.I cp
is a pointer to the printable form of the address.
.sp
.B ascii2addr(\|)
converts a printed form address into the appropriate binary form.
.br
.I af 
specifies the address family to convert into.
.I cp
is a pointer to the printed form of the address.
.I ap
is a pointer to the binary form of the address after conversion.
.sp
.B addr2hostname
returns the hostname corresponding to the given network address.
.I addr
is the address being converted.
.I len
is the length of the address.
.I af
is the address family of this address.
.sp
.B hostname2addr
returns the address corresponding to the given hostname.
.I name
is the name of the host whose address is desired.
.I af
is the address family desired.

.SH HISTORY
These commands were first suggested by Craig Partridge (BBN).
.br
This implementation and manual page were done at the US Naval Research 
Laboratory.

.SH BUGS
No known bugs.

.SH COMPATIBILITY
These functions are intended to replace the equivalent older Internet-specific
functions, such as
.IR inet_ntoa(\|) and
.IR inet_aton(\|) .
