/*
 * Copyright (C) 1997 Pretty Good Privacy, Inc.  All rights reserved.
 *
 * $Id$
 */
#ifndef _ERR_H
#define _ERR_H

#define SUCCESS 0

#define ERR_USER_NOT_FOUND       1
#define ERR_RECORD_TOO_LARGE     2
#define ERR_FILE_ERROR          3
#define ERR_NO_MEM          4
#define ERR_UNKNOWN_RESOURCE     5
#define ERR_VALUE_NOT_FOUND		 6
#define ERR_BAD_PARAM          7
#define ERR_MAPI_DLL_FAILURE	 8

#endif //_ERR_H
