.TH CMKDIR 1 ""
.SH NAME
cmkdir
.SH SYNOPSIS
.B cmkdir
[ \-\fB3\fP ]
\fIdirectory\fP
.SH DESCRIPTION
\fBcmkdir\fP creates \fIdirectory\fP and assigns to it cryptographic
keys for use by the Cryptographic File System (CFS).  Operation is
similar to the ordinary \fBmkdir\fP(1) command, with the addition that
the user is prompted for a passphrase which is used to generate the
DES keys used by cfsd(8) to transparently encrypt the files.  The
smartcard version of \fBcmkdir\fP initializes a key smartcard and
requires that a blank smartcard be inserted into the smartcard reader.
.LP
Once created, encrypted directories can be made available for use with
the \fBcattach\fP(1) command.  Users should not ordinarily read and
write directly to directories created with \fBcmkdir\fP, since these
files would not be stored in encrypted form.
.LP
By default, \fBcmkdir\fP creates directories for 2-key hybrid mode
single DES.  The \-\fB3\fP option specifies 2-key hybrid mode triple
DES; this may be more secure, albiet at the expense of performance.
Other ciphers may also be available, depending on the local
configuration.
.SH FILES
.TP
\fIdirectory\fP/...
known-plaintext hash of the assigned keys.
.TP
\fIdirectory\fP/..c
identifies the cipher algorithm.
.SH SEE ALSO
cfsd(8), cattach(1)
.SH AUTHOR
Matt Blaze; for information on cfs, email to cfs@research.att.com.

