/*____________________________________________________________________________
	Copyright (C) 1997 Network Associates, Inc. and its affiliates.
	All rights reserved.
	
	

	$Id: GUIDS.H,v 1.2.18.1 1998/11/12 03:13:56 heller Exp $
____________________________________________________________________________*/
#ifndef Included_GUIDS_h	/* [ */
#define Included_GUIDS_h

// {1C8F62A0-B699-11d0-95B0-0060977B23E7}
DEFINE_GUID(GUID_PGPPlugin, 
0x1c8f62a0, 0xb699, 0x11d0, 0x95, 0xb0, 0x0, 0x60, 0x97, 0x7b, 0x23, 0xe7);

#endif /* ] Included_GUIDS_h */


/*__Editor_settings____

	Local Variables:
	tab-width: 4
	End:
	vi: ts=4 sw=4
	vim: si
_____________________*/
