//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PGPtray.rc
//
#define IDM_TASKBARMENU                 101
#define IDD_CLIPBOARDVIEWER             104
#define IDI_TASKBAR                     105
#define IDB_BITMAP1                     115
#define IDI_TED                         116
#define IDM_TEDBARMENU                  117
#define IDB_BITMAP2                     118
#define WAV_TED1                        120
#define WAV_TED2                        122
#define WAV_TED3                        123
#define IDD_RESULTS                     124
#define IDD_LAUNCH_VIEWER               125
#define IDB_BITMAP3                     129
#define IDD_RESULTS_SMALL               131
#define IDR_MENU1                       132
#define IDD_PASSPHRASE                  1001
#define IDC_EDIT1                       1001
#define IDC_PHRASE                      1002
#define IDC_EXTERNAL_VIEWER             1002
#define IDC_HIDETYPING                  1003
#define ID_VIEW_EXTERNAL                1003
#define IDVIEW_EXTERNAL                 1003
#define IDC_PROMPTSTRING                1004
#define ID_VIEW_INTERNAL                1004
#define IDVIEW_INTERNAL                 1004
#define IDC_DECRYPTION_RESULTS          1005
#define ID_BROWSE                       1006
#define IDBROWSE                        1006
#define IDUNDO                          1007
#define IDS_SIGNATURE_ERROR             5000
#define IDS_OUT_OF_MEMORY               5001
#define IDS_FUNCTION_NOT_ENABLED        5002
#define IDS_CANNOT_SIGN_WITH_UNCERTIFIED_KEY 5003
#define IDS_CANNOT_DECRYPT_WITH_UNCERTIFIED_KEY 5004
#define IDS_CANNOT_ENCRYPT_WITH_UNCERTIFIED_KEY 5005
#define IDS_CATCHALL_ERROR_MESSAGE      5006
#define IDS_UNABLE_TO_MATCH_ID          5007
#define IDS_RSA_ENCR_ERROR              5008
#define IDS_INVALID_FILE_OP_ERROR       5009
#define IDS_NO_PGP_DATA                 5010
#define IDS_NO_DATA_TO_ENCRYPT          5011
#define IDS_HELPFILENAME                5012
#define IDS_ENTER_PHRASE                5013
#define IDS_WRONG_PHRASE                5014
#define ID_ADDKEY                       40006
#define ID_ENCRYPTSIGN                  40007
#define ID_DECRYPTVERIFY                40008
#define ID_VIEWCLIPBOARD                40009
#define ID_LAUNCHVIEWER                 40010
#define ID_LAUNCHPGPKEYS                40011
#define ID_PROPERTIES                   40012
#define ID_WHATIS_TED1                  40013
#define ID_WHATIS_TED2                  40014
#define ID_PGPTRAY_ENCRYPT              40014
#define ID_QUIT_ENCLYPTOR               40015
#define ID_HELP_TOPICS                  40016
#define ID_ENCRYPT                      40017
#define ID_SIGN                         40018
#define ID_LAUNCHPGPTOOLS               40019
#define ID_WIPECLIP                     40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
