Version 1.0 Rev A

See bugs.lst for a bug history.
    install.doc for installation

The file winsock.zip contains all the files here.

********************************************
****** This package is now shareware *******
********************************************

Send bug reports to trumpet-bugs@petros.psychol.utas.edu.au

Peter R. Tattam
