/*____________________________________________________________________________
	Copyright (C) 1997 Pretty Good Privacy, Inc.
	All rights reserved.
	
	

	$Id: STDINC.H,v 1.3 1997/07/29 20:46:38 dgal Exp $
____________________________________________________________________________*/
#ifndef Included_STDINC_h	/* [ */
#define Included_STDINC_h

// STDINC.H - project invariants

#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <richedit.h>
#include <tchar.h>

#include <mapix.h>
#include <mapiutil.h>
#include <mapiform.h>
#include <exchext.h>

#endif /* ] Included_STDINC_h */


/*__Editor_settings____

	Local Variables:
	tab-width: 4
	End:
	vi: ts=4 sw=4
	vim: si
_____________________*/
