.TH cksum 1
.SH NAME
cksum \- calculate a CRC-32 of the input
.SH SYNTAX
.B cksum
.SH DESCRIPTION
.B cksum
calculates a CRC-32 checksum of its input.

.B cksum
conforms to the
.I summain
interface.
See
.B summain(1)
for a description of
.B cksum\fP's
options.
.SH COMPATIBILITY
This program is intended to
be backwards compatible with
the POSIX
.B cksum
program.
.SH VERSION
cksum 1.0, 13 July 1993.
.SH AUTHOR
Most of the work is done in
the
.B crc32file
library,
which is
primarily code written by
Gary S. Brown.
Wrapper code
placed into the public domain by Daniel J. Bernstein.
.SH "SEE ALSO"
summain(1),
crc32file(3)
