.TH fingerprint 1
.SH NAME
fingerprint \- the universal fingerprint program
.SH SYNTAX
.B fingerprint
.SH DESCRIPTION
.B fingerprint
calculates a cryptographically strong one-way hash of its input.

.B fingerprint
conforms to the
.I summain
interface.
See
.B summain(1)
for a description of
.B fingerprint\fP's
options.
.SH VERSION
fingerprint 1.0, 7 July 1993.
.SH "SEE ALSO"
summain(1)
