.TH md5file 3
.SH NAME
md5file \- apply the RSADSI MD5 Message-Digest Algorithm to a stream
.SH SYNTAX
.B #include <md5file.h>

void \fBmd5file_clear(\fIm\fB)\fR;
.br
void \fBmd5file_add(\fIm,c\fB)\fR;
.br
void \fBmd5file_addn(\fIm,b,len\fB)\fR;
.br
void \fBmd5file_hash(\fIm,h\fB)\fR;

md5file *\fIm\fP;
.br
unsigned char \fIc\fP;
.br
unsigned char \fIh\fP[MD5FILE_HASHLEN];
.br
unsigned char *\fIb\fP;
.br
int \fIlen\fR;
.SH DESCRIPTION
.B md5file
applies the MD5 hash function
to a stream of unsigned characters.

.I m
points to an md5file structure,
which accumulates the hash as
data is fed in.
Before feeding in any data you must
call
.B md5file_clear(\fIm\fB)\fR.
Then, for each unsigned character
.I c
from the stream,
call
.B md5file_add(\fIm\fB,\fIc\fB)\fR.

To process an array
.I b
of
.I len
unsigned characters,
call
.B md5file_addn(\fIm\fB,\fIb\fB,\fIlen\fB)\fR.
This is faster than calling
.B md5file_add
on each character in turn.

.B md5file_hash(\fIm\fB,\fIh\fB)\fR
places the resulting hash into
.I h\fP,
an array of bytes of
length MD5FILE_HASHLEN.
You may not use
.I m
after that without
again calling
.B md5file_clear(\fIm\fB)\fR.

MD5FILE_HASHLEN equals 16.
.SH COMPATIBILITY
Except for minor interface differences
this should be completely compatible
with Rivest's MD5 library.
.SH DEFINITION
See RFC 1321.
.SH VERSION
md5file 0.95, 8 July 1993.
.SH AUTHOR
Derived from the RSA Data Security Incorporated
MD5 Message-Digest Function,
designed by Ron Rivest.
This adaptation created by Daniel J. Bernstein.
.SH "SEE ALSO"
mddriver(1)
