.TH summain 1
.SH NAME
summain \- generic checksum program interface
.SH SYNTAX
.I summain
[
\fB\-cgfFiIbB\fP
] [
\fIfile ...\fP
]
.SH DESCRIPTION
.I summain
is a generic interface for programs which compute checksums.
There is no actual
.B summain
program.
Instead, several other programs,
such as
.B cksum
and
.B fingerprint\fP,
all conform to
the
.I summain
interface.

.I summain
computes checksums for some number of files.
Normally it takes the filenames as arguments,
opens the files in binary mode,
computes their checksums,
and prints the checksums (with filenames) on standard output.

A checksum never contains the characters tab, space, newline, or null.
Other features of a checksum depend on the particular program.

.I summain
follows the
.B getopt
standard.
Its options are summarized here.
.TP
.B \-b
Open files in binary mode (default).
.TP
.B \-B
Open files in text mode.
.TP
.B \-i
Read filenames from input, and ignore any filename arguments.
.TP
.B \-I
Use arguments as filenames (default).
If no arguments are given,
.I summain
reads the standard input as a file.
Otherwise it ignores
the input.
.TP
.B \-f
When the
.B \-i
option is in effect,
read input lines with the
same format as the usual output
of
.I summain\fP.
In other words, look for the first tab on each input line,
and use the filename following that tab.
.TP
.B \-F
When the
.B \-i
option is in effect,
read filenames as entire input lines (default).
.TP
.B \-g
Generate checksums (default).
.I summain
will print each checksum, followed by a tab and the
name of the file,
as a separate line on standard output.
The checksum of the standard input is printed with a tab
but no filename.
.TP
.B \-c
Check checksums.
This option forces
.B \-fi\fP.
.I summain
will read any number of input lines,
each containing a purported checksum, a tab, and a filename.
.I summain
will open each file, compute its checksum, and compare the
checksum to the purported checksum.
.SH "EXIT VALUE"
0 normally.
1 for usage messages.
2 if a file could not be opened for reading.
3 with option
.B \-c
if any checksums failed to match.
(Exit value 3 overrides exit value 2.)
.SH BUGS
None known.
.SH VERSION
summain version 0.9, 13 July 1993.
.SH AUTHOR
Placed into the public domain by Daniel J. Bernstein.
.SH "SEE ALSO"
.B cksum(1)\fP,
.B fingerprint(1)\fP,
.B md5(1)\fP,
.B snefru(1)\fP
