//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by pgpwctx.rc
//
#define IDD_WORKING                     101
#define IDI_ICON_SIG                    102
#define IDI_ICON_ASC                    103
#define IDI_ICON_PGP                    104
#define IDI_ICON_PRVKR                  105
#define IDI_ICON_PUBKR                  106
#define IDI_ICON_AEXPK                  107
#define IDD_RESULTS                     124
#define IDC_PROGRESS                    1000
#define IDC_FOO_A_RAMA                  1001
#define IDC_PROGRESS_TEXT               1001
#define IDC_DECRYPTION_RESULTS          1005
#define IDS_SIGNATURE_ERROR             5000
#define IDS_OUT_OF_MEMORY               5001
#define IDS_FUNCTION_NOT_ENABLED        5002
#define IDS_CANNOT_SIGN_WITH_UNCERTIFIED_KEY 5003
#define IDS_CANNOT_DECRYPT_WITH_UNCERTIFIED_KEY 5004
#define IDS_CANNOT_ENCRYPT_WITH_UNCERTIFIED_KEY 5005
#define IDS_CATCHALL_ERROR_MESSAGE      5006
#define IDS_UNABLE_TO_MATCH_ID          5007
#define IDS_RSA_ENCR_ERROR              5008
#define IDS_INVALID_FILE_OP_ERROR       5009
#define IDS_NO_PGP_DATA                 5010
#define IDS_NO_DATA_TO_ENCRYPT          5011
#define IDS_ENTER_PHRASE                5012
#define IDS_WRONG_PHRASE                5013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
