#ifndef VALIDATE_H
#define VALIDATE_H

boolean ValidateAll();
boolean TestSettings();

boolean ZKValidate();

boolean MD5Validate();
boolean SHAValidate();
boolean HAVALValidate();
boolean TigerValidate();
boolean RIPEMDValidate();

boolean MD5MACValidate();
boolean HMACValidate();
boolean XMACCValidate();

boolean DESValidate();
boolean IDEAValidate();
boolean SAFERValidate();
boolean RC4Validate();
boolean RC5Validate();
boolean BlowfishValidate();
boolean Diamond2Validate();
boolean ThreeWayValidate();
boolean GOSTValidate();
boolean SHARKValidate();

boolean BBSValidate();
boolean DHValidate();
boolean RSAValidate();
boolean ElGamalValidate();
boolean DSAValidate();
boolean LUCValidate();
boolean RabinValidate();
boolean BlumGoldwasserValidate();
boolean ECPValidate();
boolean EC2NValidate();

#endif
