This file documents differences between Apache-SSL and Apache.

Configuration directives
------------------------

See SSLconf/conf/httpd.conf for all extra SSL directives.

mod_log_config.c
----------------

The following have been added to configurable logging:

%...{cipher}c:  cipher used (SSL_get_cipher)
%...{clientcert}c: client certificate information
%...{errcode}c: X509 verify error code
%...{errstr}c: X509 verify error string


