.\"
.\" pgp.cfg.5
.\"
.\" Copyright (C) 1997 Pretty Good Privacy, Inc.  All rights reserved.
.\"
.\" $Id: pgp.cfg.5,v 1.1.2.2.2.6 1997/08/27 03:57:37 quark Exp $
.\"
.\" Process this file with
.\" groff -man -Tascii pgp.1
.\"
.TH PGP 5.0 "JULY 1997 (v5.0)" PGP "User Manual"
.SH NAME
pgp.cfg \- Format of the configuration file used by
.BR pgp (1).
.SH DESCRIPTION
The default location for this file is ~/.pgp.  You may specify another
location by setting the environment variable
.IR PGPPATH .
SH COMMAND-LINE SPECIFICATION
All PGP applications accept these options as command-line arguments,
as well.  Command line arguments always override the configuration
file.  Options are specified with a double-dash (--) or plus (+),
followed by an equal sign (=) and the value, if appropriate.  For
example, to specify the public keyring to use on an encryption
operation:

.I pgpe -r foo@bar.baz.com --pubring=~/fooring.pkr

To turn on text mode, in an encryption:

.I pgpe -r foo@bar.baz.com --textmode
.SH OPTIONS
The following configuration options are supported, both in the
.I pgp.cfg
file and on the command line of PGP applications.  Case is not
important in specifying the variable names, but may be in specifying
filenames, depending on your operating environment.  Immediately
following each option is a description of its type:  Boolean is either
"1" or "on" or "0" or "off"; String is a string; and Integer is a
number.
.IP Armor
Boolean.  Turns ASCII armoring on or off.  The default is off.
.IP ArmorLines
Integer.  Specifies the maximum number of lines that may be contained
in an ASCII armored message.  Messages longer than this number of
lines will be broken up into multi-part ASCII armored messages.  A
value of zero indicates an unlimited number of lines.  The default is
zero.
.IP AutoServerFetch
Boolean.  If on, when adding keys with
.BR pgpk (1),
if a specified key file is not found, it is assumed to be the name of
a key to retrieve from your default key server (see
.I HTTPKeyServerHost
and
.IR HTTPKeyServerPort ,
below).  Some intelligence is attempted; even if this is on, if it is
obvious a file was intended (if the first characters are either "/" or
"./"), a fetch will not be made.  The default is on.
.IP Compress
Boolean.  Specifies whether messages should be compressed prior to
encryption.  The default is on.
.IP EncryptToSelf
Boolean.  If on, automatically encrypts all messages to your default
key, as well as to the intended recipient.  Intended to allow you to
read encrypted mail you've sent.  The default is off.
.IP FastKeyGen
Boolean.  Utilizes pre-generated prime numbers for certain initial
operations on DSS/Diffie-Hellman key generation.  This only works for
"standard" key sizes (1024, 1596 and 2048).  The default is on.  To
turn this off, use:
.I pgpk +fastkeygen=0 -g
.IP HTTPKeyServerHost
String.  The name of a keyserver to use in default lookups (see
.IR AutoServerFetch ,
above).  The default is pgpkeys.mit.edu.
.IP HTTPKeyServerPort
Integer.  The port to use for connections to the default key server as
specified in
.IR HTTPKeyServerHost ,
above.  The default is 11371, the default port for the Horowitz Key
Protocol.
.IP Language
String.  The country code of the language you wish to use.  The
default is "us."
.IP LanguageFile
String.  The file from which to load runtime strings.  The default is
"language50.txt" in your .pgp directory.  If this file does not exist,
PGP will use internal defaults.
.IP MyName
String.  The key ID you wish to be default for signing operations and
the
.I EncryptToSelf
option, above.  There is no default; however, if none is specified,
the first secret key on your secret keyring will be used for most
operations.
.IP NoBatchInvalidKeys
Boolean.  If True, batch mode will fail if the user attempts to
encrypt to a key that is invalid or not completely valid.  If false,
batch mode will use invalid keys.  Note that this option only applies
to batch mode; normally, PGP will ask the user to confirm prior to
encrypting to in an invalid key.  The default is on.
.IP PubRing
String.  Your public keyring file.  The default is "pubring.pkr" in
your .pgp directory.
.IP RandomDevice
String.  Entropy-generating device.  If present, it will be used in
favor of asking the user for keyboard input.  The default is
"/dev/random."
.IP SecRing
String.  Your secret keyring file.  The default is "secring.skr" in
your .pgp directory.
.IP WarnOnMixRSADiffieHellman
Boolean.  Warns the user if encrypting to multiple keys, one or more
of which is RSA and one or more of which is DSS/Diffie-Hellman.  The
reason for this warning is that most RSA key owners will still be
using 2.6.2, which will not properly decrypt such messages.  The
default is on.
.IP WarnOnRSARecipAndNonRSASigner
Boolean.  Warns the user if encrypting to an RSA key, but signing with
a DSS/Diffie-Hellman key.  The reason for this warning is that most
RSA key owners will still be using 2.6.2, which will not properly
decrypt such messages.  The default is on.


.SH BUGS
See
.BR pgp (1).
.SH "SEE ALSO"
.BR pgp (1),
.BR pgpe (1),
.BR pgpv (1),
.BR pgps (1),
.BR pgpk (1),
.BR pgp-integration (7),
http://www.pgp.com (US versions)
and
http://www.pgpi.com (International versions)

