-- automatically generated by posy 8.0 #7 (tiber), do not edit!

SECIF 

DEFINITIONS ::=

%{
#include "If-types.h"
%}

PREFIXES build parse print

BEGIN


AttributeType [[P AttrType *]] 
	::=
        OBJECT IDENTIFIER [[O *]]


SETOFAttributeType [[P SET_OF_AttrType *]]
	::=
        SET OF [[T SET_OF_AttrType * $ *]] <<next>>
        	AttributeType [[p element]]


AttributeValue [[P AttrValue *]] 
	::=
        ANY [[a *]]


AttributeValueAssertion [[P AttrValueAssertion *]] 
	::=
        %D{
        if (((*parm) = (AttrValueAssertion *) calloc (1, sizeof (AttrValueAssertion))) == ((AttrValueAssertion *) 0)) {
            	advise (NULLCP, "out of memory");
            	return NOTOK;
        }
        %}
        SEQUENCE
        {
                OBJECT IDENTIFIER [[O element_IF_0]],

                ANY [[a element_IF_1]]
        }


RelativeDistinguishedName [[P RDName *]]
	::=
        SET OF [[T RDName * $ *]] <<next>>
        	AttributeValueAssertion [[p member_IF_0]]


Name [[P DName *]] 
	::=
        SEQUENCE OF [[T DName * $ *]] <<next>>
        	RelativeDistinguishedName [[p element_IF_2]]


AttributeValues [[P AttrValues *]] 
	::=
        SET OF [[T AttrValues * $ *]] <<next>>
		ANY [[a member_IF_1]]


Attribute [[P Attr *]] 
	::=
        %D{
        if (((*parm) = (Attr *) calloc (1, sizeof (Attr))) == ((Attr *) 0)) {
            	advise (NULLCP, "out of memory");
            	return NOTOK;
        }
        %}
        SEQUENCE
        {
                OBJECT IDENTIFIER [[O type]],

                AttributeValues [[p values]]
        }


SETOFAttribute [[P SET_OF_Attr *]]
	::=
        SET OF [[T SET_OF_Attr * $ *]] <<next>>
        	Attribute [[p element]]


END

