Conditions of use for Apache-SSL:

In order to comply with UK export restrictions, I must be satisfied that the
end-user of this software complies with the following restrictions:

1. The software will not be used, in whole or in part, in connection with the
development, production, handling, operation, maintenance, storage, detection,
identification or dissemination of chemical, biological or nuclear weapons or
the development, production, maintenance or storage of missiles capable of
delivering such weapons.

2. The software may not be exported to the following countries:

Algeria, Angola, Argentina, Armenia, Azerbaijan, Belarus, Bosnia, Bulgaria,
Burma, China (Peoples' Republic of), Croatia, Cuba, Egypt, Estonia, Georgia,
India, Iran, Iraq, Israel, Kazakhstan, Latvia, Liberia, Libya, Lithuania,
Macedonia, Moldova, Montenegro, Nigeria, North Korea, Pakistan, Russia, Rwanda,
Serbia, Slovenia, Somalia, South Korea, Sudan, Syria, Taiwan, Tajikistan,
Turkmenistan, Ukraine, Uzbekhistan, Vietnam, Zaire.

That is, the above list cannot be exported to without a license. It may be
possible with a license.

I will therefore make this software available to anyone who:

a) is not in the above list of countries.

b) assures me that they will not be using the software for the above prohibited
purposes.

c) tells me what they will be using the software for.

d) gives me a list of sites they intend to run the software on.

e) explains their policy with regard to redistribution of the software, and the
enforcement of the above rules.

Note that I do have to be convinced by the answers!

There is an onus on me to make all reasonable enquiries. I believe that the
list above is reasonable given the nature of the software and the Internet. If
anyone has any suggestions, I would be only too pleased to hear them.

Ben Laurie <ben@algroup.co.uk>
A.L. Digital Ltd.
London
England

9/11/95
