This is a port of PGP 2.6.2 for ATARI-platforms.                    06-Jan-1995

This archive 'pgp262st.zip' contains two binaries:
1) pgp.ttp       non RSAREF-version (using rsaglue1.c)
2) pgp_rsa.ttp   RSAREF-version (using rsaglue2.c)

The file 'diff.st' contains all the patches necessary for compiling and 
linking. I used  GCC 2.5.8 and Mintlibs PL 44.
The executables should run on every ST,TT,Falcon.
'pgp.asc' and 'pgp_rsa.asc' contain my signatures of the binaries.

If you have any questions, feel free to contact me at

<hd@ms.maus.de> or <harry@hal.westfalen.de>

regards,
Harald Denker
