#ifndef VALIDATE_H
#define VALIDATE_H

boolean ValidateAll();
boolean TestEndianess();
boolean ZKValidate();
boolean MD5Validate();
boolean SHSValidate();
boolean DESValidate();
boolean IDEAValidate();
boolean RC4Validate();
boolean RC5Validate();
boolean BlowfishValidate();
boolean DiamondValidate();
boolean BBSValidate();
boolean DHValidate();
boolean RSAValidate();
boolean ElGamalValidate();
boolean DSAValidate();

#endif

