$l= $u= $config_l_pixie; $u =~ y/a-z/A-Z/; # -*- nroff -*-
print <<END
.TH $u 1
.SH NAME
$l \- supply passphrase to $config_l_pgpauto on request
.SH SYNOPSYS
.B $l
.SH DESCRIPTION
.B $l
sets up a Unix-domain socket. It prompts you for your passphrase, and
then any processes connecting to the socket will be sent the
passphrase.
.SH ENVIRONMENT
.TP
.B PGPPATH
The PGP files directory. Depending on your installation the passphrase
socket will be in a subdirectory
.B .wrapper
of this directory.
.SH WARNING
Improper use of this program will seriously compromise the security of
your RSA secret key, especially if your security is doubtful anyway.

I would advise against using this software on a system you do not
administer.

See the node
.B Security
in the Emacs Info documentation for Auto-PGP for more details.
.SH FILES
.TP
.B \$PGPPATH/.wrapper/$config_socketname
The socket on which to find the pixie listening.
.SH SEE ALSO
.BR pgp "(1), " $config_l_pgpauto "(1), " $config_l_decrypt (1),
.B $config_lisp.el
.SH AUTHOR
The Emacs Auto-PGP package was written by Ian Jackson.
Copyright 1993\-1994; for copying conditions see the GNU General
Public Licence. This software is distributed as-is with no warranty.
END
