.TH CVDES 8 "Aug 4 1993" "Linux" "MAINTENANCE COMMANDS"
.SH NAME
cvdes \- convert DES encryption of loop devices
.SH SYNOPSIS
.ad l
.B cvdes
.I file
.ad b
.SH DESCRIPTION
.B cvdes
is used to convert DES-encrypted files or block devices used with
loop devices from the encryption method used by version 0 to the one
used by later versions of the loop device patches.

The conversion is performed in-place. It is irreversible and must be
done exactly once. Repeating it will make the data unusable.
.SH WARNING
Attempts to convert with an invalid password are not detected and will
scramble the data beyond recognition.

.B cvdes
is completely untested.
.SH "SEE ALSO"
losetup(8)
