.TH DESVRFY 8 "Version 1.4" "Chalmers University"
.SH NAME
desvrfy, desvrfy3 \- Simple DES verification program.
.SH SYNOPSIS
.B desvrfy
[
.B \-v
]
.br
.B desvrfy3
[
.B \-v
]
.SH DESCRIPTION
.PP
.I desvrfy
and
.I desvrfy3
tests the DES encryption/decryption functions available in the DES library
.IR des (3).
Each function is run through a number of test that contains the mode
(encryption or decryption), a 64-bit DES key, a block of 64-bit input data and
a block of 64-bit data that is compared to the result of the function.
Each of these is also run in reverse (switch encryption to decryption and
vice versa).
.PP
The following options are known:
.TP
.B \- v
enable verbose output.
.PP
The current implementation does only test the base DES encryption/decryption
algorithm
.IR des_dea (3)
(desvrfy),
and the tripple DES  algorithm
.IR des_dea3 (3)
(desvrfy3).
.SH SEE ALSO
.IR des (3).
.SH AUTHOR
.ie t .ds O: \\kz\\h'+(\w'O'-\w'..')/2'\v'-0.8m'..\v'+0.8m'\\h'|\\nzu'O
.el .ds O: O
Stig \*(O:stholm <ostholm@ce.chalmers.se>
.br
Department of Computer Engineering
.br
Chalmers University of Technology
.SH RESTRICTIONS
This software may be freely distributed an modified, for non-commercial use,
without any restrictions from the author.
Additional restrictions due to national laws governing the use, import or
export of cryptographic software is the responsibility of the software user,
importer or exporter to follow.
