.\"#	@(#)COPYRIGHT	1.1a (NRL) 17 August 1995
.\"
.\"COPYRIGHT NOTICE
.\"
.\"All of the documentation and software included in this software
.\"distribution from the US Naval Research Laboratory (NRL) are
.\"copyrighted by their respective developers.
.\"
.\"This software and documentation were developed at NRL by various
.\"people.  Those developers have each copyrighted the portions that they
.\"developed at NRL and have assigned All Rights for those portions to
.\"NRL.  Outside the USA, NRL also has copyright on the software
.\"developed at NRL. The affected files all contain specific copyright
.\"notices and those notices must be retained in any derived work.
.\"
.\"NRL LICENSE
.\"
.\"NRL grants permission for redistribution and use in source and binary
.\"forms, with or without modification, of the software and documentation
.\"created at NRL provided that the following conditions are met:
.\"
.\"1. Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\"2. Redistributions in binary form must reproduce the above copyright
.\"   notice, this list of conditions and the following disclaimer in the
.\"   documentation and/or other materials provided with the distribution.
.\"3. All advertising materials mentioning features or use of this software
.\"   must display the following acknowledgement:
.\"
.\"	This product includes software developed at the Information
.\"	Technology Division, US Naval Research Laboratory.
.\"
.\"4. Neither the name of the NRL nor the names of its contributors
.\"   may be used to endorse or promote products derived from this software
.\"   without specific prior written permission.
.\"
.\"THE SOFTWARE PROVIDED BY NRL IS PROVIDED BY NRL AND CONTRIBUTORS ``AS
.\"IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\"TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\"PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL NRL OR
.\"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"The views and conclusions contained in the software and documentation
.\"are those of the authors and should not be interpreted as representing
.\"official policies, either expressed or implied, of the US Naval
.\"Research Laboratory (NRL).
.\"
.\"----------------------------------------------------------------------*/
.\"
.Dd October 1, 1995
.Dt AH 4
.Os NRL-IPv6
.Sh NAME
.Nm ah
.Nd IP/IPv6 Authentication Header
.Sh SYNOPSIS
.Fd #include <sys/socket.h>
.Fd #include <netinet6/in6.h>
.Fd #include <netinet6/ipsec.h>
.Ft int
.Fn setsockopt s SOL_SOCKET SO_SECURITY_AUTHENTICATION &ipsec_level sizeof(int)
.Ft int
.Fn getsockopt s SOL_SOCKET SO_SECURITY_AUTHENTICATION &ipsec_level &datalen
.Sh DESCRIPTION
The Authentication Header (referred to as
.Nm ah )
allows IP and IPv6 datagrams to be authenticated between two communicating
nodes.  Depending on the authentication algorithm used, non-repudiation
might also be provided.  Authentication prevents arbitary parties from
sending forged IP/IPv6 datagrams.  Preventing forged packets reduces risk
significantly.

Authentication header processing for outbound and inbound data is done
entirely within the kernel.  The authentication header can be used with
STREAM or DGRAM sockets in either PF_INET or PF_INET6 domains.

This implementation uses Keyed MD5 as the default algorithm for
.nm
processing.  To use other algorithms, the kernel will have to be rebuilt.
.Sh DIAGNOSTICS
In addition to errors that normally occur with
.Xr setsockopt 2 ,
programs that use
.Nm
may have the following happen as well.
.Bl -tag -width EADDRNOTAVAILxx
.It Bq Er EIPSEC
means that the system could not perform the requested security on outbound
or inbound packets.  This is a catch-all error meaning that
.Nm ipsec
failed inside the kernel.  Usually this is a result of key management not
being ready.  If an inbound packet fails authentication, or no
authentication header is on a packet where the socket requires it, the user
is NOT notified.
.El
.Sh SEE ALSO
.Xr getsockopt 2 ,
.Xr esp 4 ,
.Xr ipsec 4 ,
.Xr inet6 4 ,
.Xr key 4
.Rs
.%T IP Authentication Header
.%B RFC 1826
.%D August, 1995
.Re
.Rs
.%T IP Authentication using Keyed MD5
.%B RFC 1828
.%D August, 1995
.Re
.Sh BUGS
Perhaps these options should not be set at SOL_SOCKET, rather, set at
IPPROTO_IP.

System security level is currently a kernel compile-time option.
Eventually,
.Xr sysctl 8
should be used to select an appropriate system security level.
.Sh HISTORY
The
.Nm
protocol first appeared in NRL's
.Bx 4.4
IPv6 networking distribution.

The IPv6 extensions were written by Ran Atkinson, Dan McDonald, Craig Metz,
and Bao Phan of the U. S. Naval Research Laboratory.
