.\"#       @(#)COPYRIGHT   1.1a (NRL) 17 August 1995
.\"
.\"COPYRIGHT NOTICE
.\"
.\"All of the documentation and software included in this software
.\"distribution from the US Naval Research Laboratory (NRL) are
.\"copyrighted by their respective developers.
.\"
.\"This software and documentation were developed at NRL by various
.\"people.  Those developers have each copyrighted the portions that they
.\"developed at NRL and have assigned All Rights for those portions to
.\"NRL.  Outside the USA, NRL also has copyright on the software
.\"developed at NRL. The affected files all contain specific copyright
.\"notices and those notices must be retained in any derived work.
.\"
.\"NRL LICENSE
.\"
.\"NRL grants permission for redistribution and use in source and binary
.\"forms, with or without modification, of the software and documentation
.\"created at NRL provided that the following conditions are met:
.\"
.\"1. Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\"2. Redistributions in binary form must reproduce the above copyright
.\"   notice, this list of conditions and the following disclaimer in the
.\"   documentation and/or other materials provided with the distribution.
.\"3. All advertising materials mentioning features or use of this software
.\"   must display the following acknowledgement:
.\"
.\"        This product includes software developed at the Information
.\"        Technology Division, US Naval Research Laboratory.
.\"
.\"4. Neither the name of the NRL nor the names of its contributors
.\"   may be used to endorse or promote products derived from this software
.\"   without specific prior written permission.
.\"
.\"THE SOFTWARE PROVIDED BY NRL IS PROVIDED BY NRL AND CONTRIBUTORS ``AS
.\"IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\"TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\"PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL NRL OR
.\"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"The views and conclusions contained in the software and documentation
.\"are those of the authors and should not be interpreted as representing
.\"official policies, either expressed or implied, of the US Naval
.\"Research Laboratory (NRL).
.\"
.Dd October 1, 1995
.Dt ICMPV6 4
.Os NRL-IPv6
.Sh NAME
.Nm icmpv6
.Nd Internet Control Message Protocol (for IP version 6)
.Sh SYNOPSIS
.Fd #include <sys/socket.h>
.Fd #include <netinet6/in6.h>
.Ft int
.Fn socket AF_INET6 SOCK_RAW proto
.Sh DESCRIPTION
.Tn ICMPv6
is the error and control message protocol used
by
.Tn IPv6
and the other protocols that run on top of IPv6.  It may be accessed
through a
.Dq raw socket
for network monitoring
and diagnostic functions.
The
.Fa proto
parameter to the socket call to create an
.Tn ICMPv6
socket
is obtained from
.Xr getprotobyname 3 .
.Tn ICMPv6
sockets are connectionless,
and are normally used with the
.Xr sendto
and
.Xr recvfrom
calls, though the
.Xr connect 2
call may also be used to fix the destination for future
packets (in which case the 
.Xr read 2
or
.Xr recv 2
and 
.Xr write 2
or
.Xr send 2
system calls may be used).
.Pp
The ICMPv6 socket is not fully
.Dq raw ,
because of what the kernel does to outgoing ICMPv6 packets.  Outgoing
packets automatically have an
.Tn IPv6
header prepended to
them (based on the destination address).  Outgoing packets also have their
ICMPv6 checksum computed for them, because unlike ICMP, ICMPv6 requires a
pseudo-header checksum.  This behavior is nullified by setting the
IP_HDRINCL
.Xr setsockopt ,
which makes an ICMPv6 socket truly raw.
Incoming packets are received with the
.Tn IPv6
header and options intact.
.Sh DIAGNOSTICS
A socket operation may fail with one of the following errors returned:
.Bl -tag -width [EADDRNOTAVAIL]
.It Bq Er EISCONN
when trying to establish a connection on a socket which
already has one, or when trying to send a datagram with the destination
address specified and the socket is already connected;
.It Bq Er ENOTCONN
when trying to send a datagram, but
no destination address is specified, and the socket hasn't been
connected;
.It Bq Er ENOBUFS
when the system runs out of memory for
an internal data structure;
.It Bq Er EADDRNOTAVAIL
when an attempt is made to create a 
socket with a network address for which no network interface
exists.
.El
.Sh SEE ALSO
.Xr send 2 ,
.Xr recv 2 ,
.Xr netintro 4 ,
.Xr inet6 4 ,
.Xr ipv6 4
.Sh HISTORY
The
.Nm
protocol first appeared in NRL's 
.Bx 4.4
IPv6 networking distribution.
.Pp
The IPv6 extensions, including ICMPv6, were written by Ran Atkinson, Dan
McDonald, Craig Metz, and Bao Phan of the U. S. Naval Research Laboratory.
