.TH NSLOOK 1 "Sep 10, 1991"
.UC 4
.SH NAME
nslook \- name server lookup
.SH SYNOPSIS
.B nslook
[
.B \-l
]
[
.B \-n
]
.I hostname
.br
.B nslook
[
.B \-l
]
[
.B \-a
]
.I IP-address
.br
.SH DESCRIPTION
.B Nslook 
provides a simple way to retrieve an IP address or a host name
from the Domain Name Service. The command
.PP
.ti +10n
\fC nslook \fP
.I hostname
.PP
prints the IP address of
.I hostname
on standard output (and nothing else). The command
.PP
.ti +10n
\fC nslook \fP
.I IP-address
.PP
prints the official name of the Internet host with the specified
.I IP-address
on standard output.
.PP
If the
.B \-l
flag is given, 
.B nslook
gives a long format display, showing the host's official name, zero or
more aliases, and one or more IP addresses.
.B \-a
forces the interpretation of the argument as an address, 
.B \-n 
as a hostname. Otherwise it is treated as an address if it ``looks like'' 
an address, and as a hostname if not.
.PP
.SH DIAGNOSTICS
The diagnostics of 
.B nslook
correspond to the errors signalled by
gethostbyname(3) and gethostbyaddr(3).
.TP
\fC unknown host \fP
.TP
\fC temporary error -- try again later \fP
This usually indicates that the local server did not receive
a response from an authoritative server.
A retry at some later time may succeed.
.TP
\fC unrecoverable error \fP
Some unexpected server failure was encountered.
.TP
\fC no IP address \fP
The requested name is valid but does not have an IP address; 
this is not a temporary error.  
This means that the name is known to the name server but there is no address
associated with this name.
Another type of request to the name server using this domain name
will result in an answer;
for example, a mail-forwarder may be registered for this domain.
.PP
The exit code of 
.B nslook
in case of one these errors is the corresponding value of h_errno as defined
in /usr/include/netdb.h: HOST_NOT_FOUND, TRY_AGAIN, NO_RECOVERY, or NO_DATA
(NO_ADDRESS on some systems).
.PP
If an unknown error occurs, the exit code is 16.
In case of a usage error the exit code is 15.
.SH "SEE ALSO"
nslookup(1), gethostbyaddr(3), gethostbyname(3)
.SH FILES
/usr/include/netdb.h
.SH BUGS
Normally
.B nslook
does not list alias hostnames since it only uses the information given 
by gethostbyname(3) or gethostbyaddr(3).
.PP
If 
.B nslook
tries to find the address of a non-existent host in the local domain, 
the error ``no IP address'' is signalled. This is due to the return code 
of gethostbyname(3).
.PP
.SH AUTHOR
Juergen Nickelsen  <nickel@cs.tu-berlin.de>
