//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PGPtray.rc
//
#define IDS_PGPNET                      1
#define IDS_PGPTOOLS                    2
#define IDS_PGPDISK                     3
#define IDS_PGPKEYS                     4
#define IDS_CHECKIFOKTOCLOSE            5
#define IDS_CAPTION                     6
#define IDS_CANNOTSETPURGEHOTKEY        7
#define IDS_CANNOTSETENCRYPTHOTKEY      8
#define IDS_CANNOTSETSIGNHOTKEY         9
#define IDS_CANNOTSETENCRYPTSIGNHOTKEY  10
#define IDS_CANNOTSETDECRYPTHOTKEY      11
#define IDS_CANNOTLAUNCHPGPNET          12
#define IDS_DRIVERENABLED               13
#define IDS_DRIVERDISABLED              14
#define IDS_DRIVERNOTAVAIL              15
#define IDS_SERVICENOTRESPOND           16
#define IDS_SERVICENOTAVAIL             17
#define IDS_CHECKIFOKTOCLOSEOE          18
#define IDS_SZAPP                       19
#define IDM_TASKBARMENU                 101
#define IDM_TASKBARMENUREV              102
#define IDD_CLIPBOARDVIEWER             104
#define IDI_TASKBAR                     105
#define IDI_TRAYICON                    105
#define IDB_BITMAP1                     115
#define IDI_TED                         116
#define IDM_TEDBARMENU                  117
#define IDB_BITMAP2                     118
#define WAV_TED1                        120
#define WAV_TED2                        122
#define WAV_TED3                        123
#define IDD_RESULTS                     124
#define IDD_LAUNCH_VIEWER               125
#define IDB_BITMAP3                     129
#define IDD_RESULTS_SMALL               131
#define IDR_MENU1                       132
#define IDB_EXEBITMAP4BIT               134
#define IDB_EXEBITMAP24BIT              135
#define IDM_PGPNETPOPUP                 135
#define IDI_NETTRAYICON                 136
#define IDI_BROKENNETTRAYICON           137
#define IDD_PASSPHRASE                  1001
#define IDC_EDIT1                       1001
#define IDC_PHRASE                      1002
#define IDC_EXTERNAL_VIEWER             1002
#define IDC_HIDETYPING                  1003
#define ID_VIEW_EXTERNAL                1003
#define IDVIEW_EXTERNAL                 1003
#define IDC_PROMPTSTRING                1004
#define ID_VIEW_INTERNAL                1004
#define IDVIEW_INTERNAL                 1004
#define IDC_DECRYPTION_RESULTS          1005
#define ID_BROWSE                       1006
#define IDBROWSE                        1006
#define IDUNDO                          1007
#define IDS_SIGNATURE_ERROR             5000
#define IDS_OUT_OF_MEMORY               5001
#define IDS_FUNCTION_NOT_ENABLED        5002
#define IDS_CANNOT_SIGN_WITH_UNCERTIFIED_KEY 5003
#define IDS_CANNOT_DECRYPT_WITH_UNCERTIFIED_KEY 5004
#define IDS_CANNOT_ENCRYPT_WITH_UNCERTIFIED_KEY 5005
#define IDS_CATCHALL_ERROR_MESSAGE      5006
#define IDS_UNABLE_TO_MATCH_ID          5007
#define IDS_RSA_ENCR_ERROR              5008
#define IDS_INVALID_FILE_OP_ERROR       5009
#define IDS_NO_PGP_DATA                 5010
#define IDS_NO_DATA_TO_ENCRYPT          5011
#define IDS_HELPFILENAME                5012
#define IDS_ENTER_PHRASE                5013
#define IDS_WRONG_PHRASE                5014
#define ID_ADDKEY                       40006
#define ID_ENCRYPTSIGN                  40007
#define ID_DECRYPTVERIFY                40008
#define ID_VIEWCLIPBOARD                40009
#define ID_LAUNCHVIEWER                 40010
#define ID_PROPERTIES                   40012
#define ID_WHATIS_TED1                  40013
#define ID_WHATIS_TED2                  40014
#define ID_PGPTRAY_ENCRYPT              40014
#define ID_QUIT_ENCLYPTOR               40015
#define ID_HELP_TOPICS                  40016
#define ID_ENCRYPT                      40017
#define ID_SIGN                         40018
#define ID_WIPECLIP                     40020
#define ID_USECURRENT                   40021
#define ID_ENCRYPTCLIPBOARD             40025
#define ID_SIGNCLIPBOARD                40026
#define ID_ENCRYPTSIGNCLIPBOARD         40027
#define ID_DECRYPTVERIFYCLIPBOARD       40028
#define ID_ENCRYPTWINDOW                40029
#define ID_SIGNWINDOW                   40030
#define ID_ENCRYPTSIGNWINDOW            40031
#define ID_DECRYPTVERIFYWINDOW          40032
#define ID_LAUNCHPGPKEYS                40033
#define ID_LAUNCHPGPTOOLS               40034
#define ID_LAUNCHPGPDISK                40035
#define ID_LAUNCHPGPNET                 40036
#define ID_PGPNETHOSTS                  40037
#define ID_PGPNETLOG                    40038
#define ID_PGPNETSTATUS                 40039
#define ID_PGPNETLOGON                  40040
#define ID_PGPNETLOGOFF                 40041
#define ID_PGPNETOPTIONS                40042

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40043
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
