/*____________________________________________________________________________
	pgpPFLConfig.h  (Macintosh version)
	
	Copyright (C) 1997 Pretty Good Privacy, Inc.
	All rights reserved.
	
	This file contains the Macintosh version of the configuration file
	normally generated by the automatic configure script on Unix.

	$Id: pgpPFLConfig.h,v 1.6 1997/07/25 00:22:47 lloyd Exp $
____________________________________________________________________________*/
#ifndef Included_pgpPFLConfig_h	/* [ */
#define Included_pgpPFLConfig_h

#define HAVE_STDARG_H	1
#define HAVE_STDLIB_H	1

#if ! defined( HAVE_UNISTD_H )
#define HAVE_UNISTD_H	1
#endif

#define NO_POPEN		1

#define PATH_MAX		255



#endif /* ] Included_pgpPFLConfig_h */

/*__Editor_settings____

	Local Variables:
	tab-width: 4
	End:
	vi: ts=4 sw=4
	vim: si
_____________________*/
