.T1 unshar 1L
.SH NAME
unshar \- extract files from shell archive(s)
.SH SYNTAX
unshar [\-t] [\-b] [-v] [-xfile] [file(s)]
.SH OPTIONS
Options are processed by
.B getopts(3).
.TP 8
.B \-t   
Do not extract files, just list the files in the archive(s).
.TP
.B \-b
Extract files from the archive(s) brutally, with no regard at all to things
such as testing if the file exists, or chmoding the file etc. Currently
this is the only method supported, but other methods would be easy to add.
.TP
.B \-v
Be verbose. Used only for debugging purposes.
.TP
.B \-xfile
Extract the named file from the shell archive. If the \-x flag is used,
only those files specified will be extracted.
.SH DESCRIPTION
.I Unshar
extracts files from one or more shell archives, and places them in the current
directory. It does no forking to achieve this, and is relatively fast.
If no file name is given as an agrumemt,
.I unshar
will use standard input.
At the moment
.I unshar
is very simple-minded, and does its extraction rather brutally. The code
has been written to allow more intelligent unarchiving methods to be
added.
.SH SEE ALSO
shar(1), sh(1).
