.\" Copyright (C) 1990 Kevin R. Coombes and David R. Grant
.\" Distributed under the terms of the GNU General Public License as
.\" published by the Free Software Foundation, without any warranty.
.TH Quadratic 3 "12 March 1990"
.SH NAME
quadratic, Dadd, Dsub, Dmult, Dminus, Deq, Norm, Dinitial \- arbitrary precision arithmetic over the ring of integers ina quadratic number field
.SH SYNOPSIS
.nf
.B #include "Dstruct.h"
.LP
.B quad Dadd(a, b)
.B quad a, b;
.LP
.B quad Dsub(a, b)
.B quad a, b;
.LP
.B quad Dmult(a, b)
.B quad a, b;
.LP
.B quad Dminus(a)
.B quad a;
.LP
.B char Deq(a, b)
.B quad a, b;
.LP
.B unsigned short *Norm(a)
.B quad a;
.LP
.B void Dinitial(d)
.B long d;
.fi
.SH DESCRIPTION
These routines provide access to multi-precision arithmetic in the ring 
of integer of a quadratic number field. they use the 
.I Arithmetic
package for the multi-precision part. Any routines which make use of this
package must begin by setting the value of 
.I d
whose square root is to be adjoined by a call to
.B Dinitial(\|).
.LP
.BR Dadd(\|),
.B Dsub(\|),
and
.B Dmult(\|)
return the sum, difference, and product, respectively of their arguments.
.BR Dminus(\|)
returns the negative of its argument.
.BR Norm(\|)
returns a very long integer which is the norm in the rational numbers of its
argument.
.SH FILES
.nf
.B Dstruct.h
.B integer.h
.B utility.h
.B libZ.a
.B libU.a
.fi
.SH "SEE ALSO"
arithmetic(3), rational(3), warehouse(3)

