This is a port of PGP263i for the ATARI ST/TT/Falcon.
Patchlevel a as of 1996/03/04

The archive contains two binaries:
PGP.TTP    version for 68000
PGP020.TTP version for 68020 (and higher)

PGP263II.ASC is the signature for the internal archive PGP263II.ZIP
To check those signatures, you need my public key. It is included in
the file GEENS.ASC

Questions and other feedback can be directed to:

<guy.geens@elis.rug.ac.be>

Regards,

Guy Geens

