.TH RSA 1L
.SH TITLE
rsa, genprim, genrsa, rsaencode, rsadecode \- support RSA message encryption
.SH SYNOPSIS
\fBrsaencode\fR \fIpublic\fR
.br
\fBrsadecode\fR \fIsecret\fR
.br
\fBrsakeys\fR [\fB-l\fR \fIlength\fR] [\fB-P\fR \fIprob\fR] [\fB-s\fR \fIsecret\fR] [\fB-p\fR \fIpublic\fR]
.br
\fBgenprim\fR \fIlength\fR \fIprob\fR
.br
\fBgenrsa\fR
.SH DESCRIPTION
The RSA programs provide facilities for RSA encryption and decryption of data.

.B rsaencode
encrypts data supplied on the standard input
and writes the encrypted data to the standard output.
It takes as argument
.IR public ,
the name of a file containing the public RSA encryption keys.

.B rsadecode
decrypts data supplied on the standard input
and writes the drcrypted data to the standard output.
It takes as argument
.IR secret ,
the name of a file containing the secret RSA encryption keys.

.B rsakeys
creates two files containing the public and secret keys
used for encryption and decryption.
By default these are in
.B $HOME/.rsapublic
and
.B $HOME/.rsasecret
respectively, or as specified by the environment variables
.B $RSAPUBLIC
and
.B $RSASECRET
if set.
.B rsakeys
takes the following options:
.TP
\fB-l\fR \fIlength\fR
The length of the base primes used to generate the keys, default 10.
.TP
\fB-P\fR \fIprob\fR
Specify that the probability that the base primes are not actually prime
should be 1 in 2^\fIprob\fR, default 1 in 2^20.
.TP
\fB-s\fR \fIsecret\fR
Specify that the secret keys, used for decryption, are to be stored in the file
.I secret
instead of the default outlined above.
.TP
\fB-p\fR \fIpublic\fR
Specify that the public keys, used for encryption, are to be stored in the file
.I public
instead of the default outlined above.
.P
.B genprim
is used internally by
.B rsakeys
to generate probable primes for use as seeds to generate keys
for the encryption and decryption processes.
It places the prime on the standard output.
.B genrsa
takes two arguments:
.TP
.I length
The length of the prime to be generated.
.TP
.I prob
Specify that the probability that the number generated is not actually prime
should be 1 in 2^\fIprob\fR.
.P
.B genrsa
reads two primes from its standard input, separated by a delimiter,
and writes three numbers to its standard output, separated by the same delimiter.
The first two numbers constiute the secret keys,
the first and third numbers the public key.
.SH BUGS
The encryption/decryption process seems to pad the decrypted message
with NULs to a block boundary.

Pure RSA encryption is used. I mean, we don't use DES or any other cipher to
speed up the process. This means that the encryption process is slow.
.SH FILES
.TP
.B ${RSASECRET-$HOME/.rsasecret}
Location of secret keys, used by \fBrsakeys\fR.
.TP
.B ${RSAPUBLIC-$HOME/.rsapublic}
Location of public keys, used by \fBrsakeys\fR.
.SH AUTHOR
Mein Wissen ueber RSA und die anderen verwendeten Verfahren hab ich aus:
.nf
	Horster, Patrick:
	Kryptologie / von Patrick Horster. - Mannheim;
	Wien; Zuerich: Bibliographisches Institut, 1985.
	    (Reihe Informatik; 47)
	    ISBN 3-411-03106-9
	NE: GT

Martin Nicolay		( martin@trillian.megalon.de )
Fliederstr. 23
4100 Duisburg 1
W-Germany
.fi
