pgp challeng.sig challeng.enc
pgp copying.sig copying.txt 
pgp crc_cpp.sig crc.c     
pgp crc_h.sig crc.h       
pgp def.sig def.h
pgp diamondc.sig diamond.c
pgp diamondd.sig diamond.dat 
pgp diamondh.sig diamond.h
pgp diamondp.sig diamond.ps
pgp diamondt.sig diamond.txt
pgp dlocksun.sig dlock       
pgp dlockcpp.sig dlock.c   
pgp dlockexe.sig dlock.exe   
pgp dlocktxt.sig dlock.txt   
pgp makdlock.sig makdlock.bat
pgp thesis.sig thesis.txt

