.\"                                                                   
.\" Filename:      find_shortid.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:43:28 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   


.Dd May 17, 1997
.Dt FIND_SHORTID 3
.Os PGPlib
.Sh NAME
.Nm find_shortid
.Nd find a short KeyID
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn find_shortid "char *key" "PGPKEYID *keyid"
.Sh DESCRIPTION
The null terminated string 
.Fa key
must be on the form
.Fa 0[Xx]12345678
(e.g., a 32 bit number (in hex), represented in ASCII).
It is converted into an u_long by means of 
.Fn strtoul 3 .
This value is then used to find a matching real key identifier (64
bits long).
.Pp
.Sh RETURN VALUES
If a matching real key identifier is found it is written into
.Fa keyid
and 0 is returned.
If an error occurs, -1 is returned.
.Pp
.Sh SEE ALSO
.Xr dbopen 3
.Xr keydb_init 3
.Xr strtoul 3
.Pp
.Sh BUGS
There are only 2^32 possible "short" key identifiers while there are
2^64 possible real ones.
The caller must assure himself that the correct key was indeed
returned. 
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
                                                                    
