.\"                                                                   
.\" Filename:      free_keyrecord.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Nov  8 18:25:57 1997
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   

.Dd November 7, 1997
.Dt free_keyrecord 3
.Os PGPlib
.Sh NAME
.Nm free_keyrecord
.Nd Free an array of keyrecords
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft void
.Fn free_keyrecords "keyent_t ***records"
\.
.Sh DESCRIPTION
The array of pointers to records containing keys, as returned from
.Fn get_only_pubkey
and
.Fn is_compromised ,
is properly freed.
\.
.Sh SEE ALSO
.Xr get_only_pubkey PGPlib
.Xr is_compromised PGPlib
.Xr get_keycontents PGPlib
\.
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
