.\"                                                                   
.\" Filename:      get_keycontents.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:45:53 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   


.Dd May 17, 1997
.Dt get_keycontents 3
.Os PGPlib
.Sh NAME
.Nm get_keycontents
.Nd get the contents of a public key
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn get_keycontents "PGPKEYID id" "keyent_t ***ent"
.Sh DESCRIPTION
Retrieves the public key
.Fa id
from the database and parses it.  The different packages associated
with the key are also retrieved.  All this information is then returned
as an array of pointers to structures.
.Fa ent
is set to point to this array.
All the memory is allocated by means of malloc and should be freed
when no longer needed.  This is conveniently performed by
.Fn free_keyrecords .
.Pp
.Sh RETURN VALUES
If the retrival was successful, 0 is returned.  If no key was found, 1
is returned.  If an error occured, -1 is returned.
.Pp
.Sh SEE ALSO
.Xr get_keyent_from_buffer PGPlib
.Xr get_pub_key_rec PGPlib
.Xr free_keyrecords PGPlib
.Xr PGPlib 3
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
