.\"                                                                   
.\" Filename:      get_only_pubkey.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:45:52 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   


.Dd May 17, 1997
.Dt GET_ONLY_PUBKEY 3
.Os PGPlib
.Sh NAME
.Nm get_only_pubkey
.Nd get a public key without signatures and UID's
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn get_only_pubkey "PGPKEYID id" "PGPpubkey_t **key"
.Sh DESCRIPTION
The public key
.Fa id
is retrieved from the database.  The space taken up by the key has
been allocated by means of malloc.
.Pp
.Sh RETURN VALUES
If the key was found and no error occured, 0 is returned.
If the key was not found, 1 is returned.
If an error occured, -1 is returned.
.Pp
.Sh SEE ALSO
.Xr free 3
.Xr get_pubkey_rec 3
.Xr malloc 3
.Sh STANDARDS
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
                                                                    
