.\"                                                                   
.\" Filename:      is_compromised.3
.\" Description:   
.\" Author:        Tage Stabell-Kuloe <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:44:51 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright University of Tromsø (Norway)
.\" 	See the file COPYING for details
.\"                                                                   

.Dd December 8, 1997
.Dt IS_COMPROMISED 3
.Os PGPlib
.Sh NAME
.Nm is_compromised
.Nd verify that a key is not compremosed
.Sh SUNOPSIS
.Ft int
.Fn is_compromised "PGPKEYID key_id"
.Sh DESCRIPTION
It is verified that no signature on the public key with identification
.Fa key_id
is signed with the key itself (without a userid assosiation).
A database with keys must be available.
.Pp
.Sh RETURN VALUES
If no compromise certificate was found, 0 is returned.
If the key is compromised, 1 is returned.
Upon error, -1 is returned.
.Pp HISTORY
Written by Thomas Roessler <roessler@guug.de>.  First appeared in
PGPlib 1.0.

