.\"                                                                   
.\" Filename:      keydb_end.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Nov  8 18:29:58 1997
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" (C) 1997 Tage Stabell-Kulø, all rights reserved.
.\"                                                                   


.Dd May 14, 1997
.Dt KEYDB_END 3
.Os PGPlib
.Sh NAME
.Nm keydb_end
.Nd close a database of public keys 
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft void
.Fn keydb_end "void"
.Sh DESCRIPTION
The databases opened with
.Fn keydb_init
are properly closed.
.Pp
.Sh SEE ALSO
.Xr dbopen 3
.Xr keydb_init PGPlib
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
.Pp
.Sh BUGS
The databases, when used, are a global resource.  This means that some
other means is required to avoid race conditions.
