.\"                                                                   
.\" Filename:      make_ctb.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Nov  8 18:42:52 1997
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   

.Dd May 17, 1997
.Dt MAKE_CTB 3
.Os PGPlib
.Sh NAME
.Nm make_ctb
.Nd make a CTB based on packet type
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn make_ctb "u_char type" "u_long length" "int force" "u_char *buf"
.Sh DESCRIPTION
The length of the length of a PGP packet depends on the length
of the data, and the type.  Take a type, a length and a buffer (at
least 5 bytes long) and write a CTB and the length (in network byte
order) into the buffer.
If 
.Fa force
is non-zero the length of the length is set to 4 regardless of type.
.\.
.Sh RETURN VALUES
The number of bytes written into
.Fa buf 
is returned.
.\
.Sh SEE ALSO
.Xr PGPlib 3
.\.
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1.
The idea was taken from 
.Fn write_ctb_len
in PGP/src/crypto.c
