.\"                                                                   
.\" Filename:      uids_from_keyid.3
.\" Description:   
.\" Author:        Tage Stabell-Kulo <tage@acm.org>
.\" Modified at:   Sat Jan 24 18:45:48 1998
.\" Modified by:   Tage Stabell-Kuloe <tage@acm.org>
.\" 	
.\" 	Copyright (c) Univerity of Tromsø, Norway
.\" 	See the file COPYING for details
.\"                                                                   


.Dd May 17, 1997
.Dt UIDS_FROM_ID 3
.Os PGPlib
.Sh NAME
.Nm uids_from_id
.Nd find all UID's associated with a public key
.Sh SYNOPSIS
.Fd #include <pgplib.h>
.Ft int
.Fn uids_from_keyid "PGPKEYID id" "PGPuserid_t ***uidpp"
.Sh DESCRIPTION 
The public key record
.Fa id
is fetched and all associated user identifications are exctracted.
Upon sucessful return, 
.Fa uidpp
points to an array of pointers to structures holding user
identifications.
The array is NULL terminated.
Both the array, the structures and their contents have been allocated
by means of malloc and should be free'ed when no longer needed.
.Pp
.Sh RETURN VALUES
If nothing goes wrong, 0 is returned.  Otherwise, -1 is returned.
.Pp
.Sh SEE ALSO
.Xr free 3
.Xr free_uid PGPlib
.Xr get_pubkey_rec PGPlib
.Xr malloc 3
.Xr PGPlib 3
.Pp
.Sh HISTORY
Written by Tage Stabell-Kulø.  First appeared in PGPlib 0.1
