.\" Copyright (C) 1994-1997  Richard Gooch
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.

.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" Richard Gooch may be reached by email at  rgooch@atnf.csiro.au
.\" The postal address is:
.\"   Richard Gooch, c/o ATNF, P. O. Box 76, Epping, N.S.W., 2121, Australia.
.\"
.\"	pgpsign.1		Richard Gooch	30-SEP-1997
.\"
.TH PGPSIGN 1 "30 Sep 1997" "PGPsendmail/Unix Suite"
.SH NAME
pgpsign \- sign PGP messages
.SH SYNOPSIS
.B pgpsign
.SH DESCRIPTION
The \fIpgpsign\fP programme will sign an ASCII message using PGP,
without the need for a passphrase. It uses PGPdaemon to actually
perform the signing. \fIpgpsign\fP is simply a front-end to
PGPdaemon. PGPdaemon is part of the PGPsendmail/Unix Suite.
\fIpgpsign\fP will read the standard input for the ASCII message
and will write the signed message to the standard output.
\fIpgpsign\fP will only sign one message.
.SH FILES
.PD 0
.TP 30
.BI $PGPPATH/secring.pgp
the users' secret keyring file
.TP
.BI pgpsendmail/doc/README.PGPdaemon
distribution README (has more info.)
.PD
.SH SEE ALSO
.BR sendmail (8),
.BR pgp (1),
.BR pgpsendmail (1),
.BR pgpdaemon (1),
.BR sendpgppass (1),
.BR pgppipe(1)
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au) wrote pgppipe(1) which was copied
and modified by Antony Towns to create pgpsign(1).
.SH AVAILABILITY
The PGPsendmail/Unix Suite is available for anonymous ftp from:

ftp.atnf.csiro.au:pub/people/rgooch
ftp.dhp.com:pub/crypto/pgp/PGPsendmail
ftp.ox.ac.uk:pub/crypto/pgp/utils
linux.nrao.edu:pub/src/pgp/PGPsendmail
