.TH crc32file 3
.SH NAME
crc32file \- apply the standard CRC-32 hash function to a stream
.SH SYNTAX
.B #include <crc32file.h>

void \fBcrc32file_clear(\fIm\fB)\fR;
.br
void \fBcrc32file_add(\fIm,c\fB)\fR;
.br
void \fBcrc32file_addn(\fIm,b,len\fB)\fR;
.br
void \fBcrc32file_hash(\fIm,h\fB)\fR;

crc32file *\fIm\fP;
.br
unsigned char \fIc\fP;
.br
unsigned char \fIh\fP[CRC32FILE_HASHLEN];
.br
unsigned char *\fIb\fP;
.br
int \fIlen\fR;
.SH DESCRIPTION
.B crc32file
applies the standard CRC-32 hash function
to a stream of unsigned characters.

.I m
points to an crc32file structure,
which accumulates the hash as
data is fed in.
Before feeding in any data you must
call
.B crc32file_clear(\fIm\fB)\fR.
Then, for each unsigned character
.I c
from the stream,
call
.B crc32file_add(\fIm\fB,\fIc\fB)\fR.

To process an array
.I b
of
.I len
unsigned characters,
call
.B crc32file_addn(\fIm\fB,\fIb\fB,\fIlen\fB)\fR.
This is faster than calling
.B crc32file_add
on each character in turn.

.B crc32file_hash(\fIm\fB,\fIh\fB)\fR
places the resulting hash into
.I h\fP,
an array of bytes of
length CRC32FILE_HASHLEN.
You may not use
.I m
after that without
again calling
.B crc32file_clear(\fIm\fB)\fR.

CRC32FILE_HASHLEN equals 4.
.SH COMPATIBILITY
The
.B crc32file
library was designed for compatibility with
BSD 4.4
.B cksum\fR.
.SH DEFINITION
See the POSIX specification for
.B cksum\fR.
.SH VERSION
crc32file 0.95, 8 July 1993.
.SH AUTHOR
Interface by Daniel J. Bernstein
to code written by Gary S. Brown.
.SH "SEE ALSO"
cksum(1)
