/*____________________________________________________________________________
	Copyright (C) 1997 Network Associates Inc. and affiliated companies.
	All rights reserved.

	$Id: STDINC.H,v 1.4 1999/03/10 03:03:17 heller Exp $
____________________________________________________________________________*/
#ifndef Included_STDINC_h	/* [ */
#define Included_STDINC_h

// STDINC.H - project invariants

#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <richedit.h>
#include <tchar.h>

#include <mapix.h>
#include <mapiutil.h>
#include <mapiform.h>
#include <exchext.h>

#endif /* ] Included_STDINC_h */


/*__Editor_settings____

	Local Variables:
	tab-width: 4
	End:
	vi: ts=4 sw=4
	vim: si
_____________________*/
