.TH fingerprintfile 3
.SH NAME
fingerprintfile \- compute the fingerprint of a stream
.SH SYNTAX
.B #include <fprintfile.h>

void \fBfingerprintfile_clear(\fIf\fB)\fR;
.br
void \fBfingerprintfile_addn(\fIm,b,len\fB)\fR;
.br
void \fBfingerprintfile_add(\fIf\fB,\fIc\fB)\fR;
.br
void \fBfingerprintfile_hash(\fIf\fB,\fIh\fB)\fR;

unsigned int \fBfingerprintfile_fmt(\fIs\fB,\fIh\fB)\fR;
.br
unsigned int \fBfingerprintfile_scan(\fIs\fB,\fIh\fB)\fR;

fingerprintfile *\fIf\fP;
.br
unsigned char \fIc\fP;
.br
unsigned char \fIh\fP[FINGERPRINTFILE_HASHLEN];
.br
unsigned char *\fIb\fP;
.br
int \fIlen\fR;

char *\fIs\fP;
.SH DESCRIPTION
.B fingerprintfile
computes the fingerprint
of a stream of unsigned characters.

Nobody knows how to create two files with the same fingerprint.

.I f
points to an fingerprintfile structure,
which accumulates the fingerprint as
data is fed in.
Before feeding in any data you must
call
.B fingerprintfile_clear(\fIf\fB)\fR.
Then, for each unsigned character
.I c
from the stream,
call
.B fingerprintfile_add(\fIf\fB,\fIc\fB)\fR.

To process an array
.I b
of
.I len
unsigned characters,
call
.B fingerprintfile_addn(\fIm\fB,\fIb\fB,\fIlen\fB)\fR.
This is faster than calling
.B fingerprintfile_add
on each character in turn.

.B fingerprintfile_hash(\fIf\fB,\fIh\fB)\fR
places the resulting fingerprint into
.I h\fP,
an array of bytes of
length FINGERPRINTFILE_HASHLEN.
You may not use
.I f
after that without
again calling
.B fingerprintfile_clear(\fIf\fB)\fR.

FINGERPRINTFILE_HASHLEN equals 57.

.B fingerprintfile_fmt(\fIs\fB,\fIh\fB)\fR
places a readable version of the hash
.I h
into the character array
.I s\fP.
It returns the number of characters written.
If
.I s
is zero,
.B fingerprintfile_fmt
will not write anything,
but it will return the number of characters it would have written.

.B fingerprintfile_scan(\fIs\fB,\fIh\fB)\fR
attempts to decipher a readable hash
appearing in the character array
.I s\fP.
If it fails it returns 0.
If it succeeds it places the hash
into
.I h\fP,
and returns the number of characters read
from
.I s\fP.

The readable version of a hash
takes up exactly 76 characters.
.SH VERSION
fingerprintfile 0.95, 8 July 1993.
.SH DEFINITION
The fingerprint contains four pieces of information:
the result of
.B snefrufile\fR,
which
(through
.B snefru512\fR)
computes the Snefru-8 function
with code derived from the Xerox Secure Hash Function;
the result of
.B md5file\fR,
which computes the
RSADSI MD5 Message-Digest Algorithm;
the result of
.B crc32file\fR,
which computes a standard CRC-32;
and the number of bytes of the stream, modulo terabytes.
.SH AUTHOR
Placed into the public domain by Daniel J. Bernstein.
Note that the libraries used by
.B fingerprintfile
are not public-domain.
.SH "SEE ALSO"
fingerprint(1),
crc32file(3),
md5file(3),
snefrufile(3)
