.TH md5 1
.SH NAME
md5 \- the RSADSI MD5 Message-Digest Algorithm
.SH SYNTAX
.B md5
.SH DESCRIPTION
.B md5
calculates a cryptographically strong one-way hash of its input.

.B md5
conforms to the
.I summain
interface.
See
.B summain(1)
for a description of
.B md5\fP's
options.
.SH VERSION
md5 1.0, 7 July 1993.
.SH AUTHOR
Most of the work is done in
the
.B md5file
library,
which is derived from the
RSADSI MD5 Message-Digest Algorithm
designed by
Ron Rivest.
Wrapper code
placed into the public domain by Daniel J. Bernstein.
.SH "SEE ALSO"
summain(1),
md5file(3)
