.TH snefru512 3
.SH NAME
snefru512 \- apply the Xerox Secure Hash Function to a 512-bit block
.SH SYNTAX
.B #include <snefru512.h>

void \fBsnefru512_setup()\fR;

void \fBsnefru512(\fIout\fB,\fIin\fB,\fIlev\fB)\fR;

snefru512_word \fIout\fP[8];
.br
snefru512_word \fIin\fP[16];
.br
int \fIlev\fP;
.SH DESCRIPTION
.B snefru512
is derived from the Xerox Secure Hash Function.
It hashes a 512-bit block
.I in
into a 256-bit block
.I out\fP.
The hash function is cryptographically strong.

To hash
.I in
into
.I out\fP,
call
.B snefru512(\fIout\fB,\fIin\fB,\fIlev\fB)\fR.
.I out
and
.I in
are arrays of
8 and 16
snefru512_words respectively.
snefru512_word
is a 32-bit unsigned integer type.

.I lev
is the Snefru security level,
any number from 2 through 8.
Snefru-2 is fast but insecure.
Snefru-4 might not be safe against
attacks by powerful future computers.
Snefru-8 is very strong and not too slow for most applications.

Before calling
.B snefru512
you must call
.B snefru512_setup()\fR.
You may call
.B snefru512_setup()
any number of times.

The
Snefru algorithm
was designed by Ralph C. Merkle.
It is named after a Pharaoh of ancient Egypt.
Merkle is offering a large cash reward to anyone who
can break Snefru-4.
.SH DEFINITION
See Ralph C. Merkle,
.I A Fast Software One-Way Hash Function\fP.
.SH VERSION
snefru512 1.0, 1 June 1993.
.SH AUTHOR
This code is essentially the same as
Merkle's reference Snefru 2.0 implementation,
as modified by Rich Salz,
together with the Snefru 2.5 S boxes.
This adaptation was created by Daniel J. Bernstein.
.SH "SEE ALSO"
snefrufile(3)
