.TH snefrufile 3
.SH NAME
snefrufile \- apply the Xerox Secure Hash Function to a stream
.SH SYNTAX
.B #include <snefrufile.h>

void \fBsnefrufile_clear(\fIs\fB)\fR;
.br
void \fBsnefrufile_add(\fIs,c\fB)\fR;
.br
void \fBsnefrufile_addn(\fIm,b,len\fB)\fR;
.br
void \fBsnefrufile_hash(\fIs,h\fB)\fR;

snefrufile *\fIs\fP;
.br
unsigned char \fIc\fP;
.br
unsigned char \fIh\fP[SNEFRUFILE_HASHLEN];
.br
unsigned char *\fIb\fP;
.br
int \fIlen\fR;
.SH DESCRIPTION
.B snefrufile
provides a standard way to apply
Merkle's
Snefru-8 hash function
to a stream of unsigned characters.

.I s
points to a snefrufile structure,
which accumulates the hash as
data is fed in.
Before feeding in any data you must
call
.B snefrufile_clear(\fIs\fB)\fR.
Then, for each unsigned character
.I c
from the stream,
call
.B snefrufile_add(\fIs\fB,\fIc\fB)\fR.

To process an array
.I b
of
.I len
unsigned characters,
call
.B snefrufile_addn(\fIm\fB,\fIb\fB,\fIlen\fB)\fR.
This is faster than calling
.B snefrufile_add
on each character in turn.

.B snefrufile_hash(\fIs\fB,\fIh\fB)\fR
places the resulting hash into
.I h\fP,
an array of bytes of
length SNEFRUFILE_HASHLEN.
You may not use
.I s
after that without
again calling
.B snefrufile_clear(\fIs\fB)\fR.

SNEFRUFILE_HASHLEN equals 32.
.SH COMPATIBILITY
The
.B snefrufile
library
was designed for compatibility
with Merkle's original
.B snefru
utility.
.SH VERSION
snefrufile 0.95, 8 July 1993.
.SH AUTHOR
Placed into the public domain by Daniel J. Bernstein.
.B snefrufile
is simply a wrapper around
.B snefru512\fR,
which is derived from the Xerox Secure Hash Function.
.SH "SEE ALSO"
snefru(1),
snefru512(3)
