.TH snefru 1
.SH NAME
snefru \- the Xerox Secure Hash Function, version 2.5a
.SH SYNTAX
.B snefru
.SH DESCRIPTION
.B snefru
calculates a cryptographically strong one-way hash of its input.

.B snefru
conforms to the
.I summain
interface.
See
.B summain(1)
for a description of
.B snefru\fP's
options.
.SH COMPATIBILITY
This is a clone of
Ralph Merkle's
.B snefru
program.
If you find two inputs which produce the same output,
please
verify first that
Merkle's version produces the same output,
and then contact
him at
merkle@parc.xerox.com.
.SH VERSION
snefru 1.2, 7 July 1993.
.SH AUTHOR
Most of the work is done in
the
.B snefrufile
and
.B snefru512
libraries,
which are
derived from the Xerox Secure Hash Function
as implemented by Merkle.
Wrapper code
placed into the public domain by Daniel J. Bernstein.
.SH "SEE ALSO"
summain(1),
snefrufile(3),
snefru512(3)
